language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

# Avoid timeouts by breaking linting into smaller chunks and using colored output
script:
  - travis_wait 30 pylint $(git ls-files '*.py') --output-format=colorized


